bilby-dev/bilby

bilby/gw/utils.py, test/gw/utils_test.py
This PR fixes a long-standing typo in the definition of `ln_i0`.
This is also intended as a test of a system to get changes on GitHub back to git.ligo.org
=> BUG: fix typo in ln_i0

bilby/core/prior/dict.py, bilby/core/prior/joint.py, bilby/core/utils/io.py, test/core/prior/dict_test.py, test/core/prior/prior_files/joint_prior.prior
This pull request addresses multiple issues with the subclassing of  BaseJointPrior lists and their reinitialization from `json` or `dict` outlined in https://github.com/bilby-dev/bilby/issues/31, implements fixes and also test cases that fail with the old implementation.
The tests uncovered some new issues that required fixes beyond the (current) discussion in https://github.com/bilby-dev/bilby/issues/31. The fixes are implemented by moving some of the logic used to re-initialize (subclasses of) `BaseJointPriorDist` from `MultivariateGaussianDist` to `BaseJointPriorDist`.
The tests also uncovered a problem with `__eq__` for `JointPrior` that resulted in `__eq__` giving `False` if the `dist` keyword does not point to the same instance. This, I felt, was inconsistent with the usage of …
=> BUGFIX: Joint prior subclassing fixes

bilby/core/sampler/nessai.py, bilby/core/sampler/polychord.py, docs/plugins.txt, docs/samplers.txt
In preparation for removing the nessai and pypolychord interfaces, I've added warnings whenever they are used.
Related to https://github.com/bilby-dev/bilby/issues/795 and https://github.com/bilby-dev/bilby/issues/774
Original GitLab MR: https://git.ligo.org/lscsoft/bilby/-/merge_requests/1381
=> MAINT: add sampler deprecation warning

README.rst
Add a permanent slack invite link to the README.
I think this will encourage people to join and also save us having to manually invite people.
=> DOC: add invite link for slack

bilby/gw/conversion.py
I noticed that we have two consecutive
```python
if likelihood is not None:
```
statements, so I've just removed the second one.
=> MAINT: remove unnecessary line in conversion

bilby/gw/detector/calibration.py, bilby/gw/prior.py, test/gw/detector/calibration_test.py
This PR aims to add sufficient flexibility in reading calibration data products to make sure that we correctly map these to the templates in the likelihood. There are probably additional documentation changes that we will want.
=> FEAT: add argument to specify calibration correction direction

bilby/core/result.py
Addresses #836 
As far as I can tell, the issue is due to a bug in bilby_pipe, but I noticed that there is already a function to remove matplotlib errors in bilby/core/result.py.
This PR simply adds a line to this function to convert "\\" into "\".
Either way I think this is a good thing to have, as I can't think of a scenario where having "\\" in a matplotlib latex string is a good idea.
=> Remove double-backslashes from latex labels passed to matplotlib.

bilby/core/sampler/dynesty_utils.py
@lalit-pathak reported the following error. This happens when no points are accepted during the MCMC while using ACT-walk. This is most likely a sign of some underlying pathology in the likelihood/sampling space, but we should handle the case smoothly.
```python
Traceback (most recent call last):
File "/home/lalit.pathak/.conda/envs/gwsim_env/lib/python3.10/multiprocessing/pool.py", line 125, in worker
result = (True, func(*args, **kwds))
File "/home/lalit.pathak/.conda/envs/gwsim_env/lib/python3.10/multiprocessing/pool.py", line 48, in mapstar
return list(map(*args))
File "/home/lalit.pathak/.conda/envs/gwsim_env/lib/python3.10/site-packages/bilby/core/sampler/dynesty_utils.py", line 198, in __call__
while self.cache[0][2] < args.loglstar:
File …
```
=> BUG: ensure infinite ACT estimates are properly handled

bilby/gw/likelihood/multiband.py, test/gw/likelihood/marginalization_test.py
This MR implements time marginalization into multiband likelihood. Time marginalization for multiband may be useful since the slow down factor of time marginalization is not as large as that for ROQ or relative binning. The plots below show the likelihood evaluation time of multiband/standard likelihood and with/without time marginalization for 16s XPHM, 64s XPHM, and 128s Pv2_NRtidalv2. The slow down is less than 2 for the first 2 cases.
=> ENH: implement time marginalization into multiband likelihood

bilby/core/prior/base.py, bilby/gw/cosmology.py, test/core/prior/dict_test.py, test/core/prior/prior_files/prior_with_cosmo_params.prior
As it stands, `get_cosmology` does not support the same inputs as `set_cosmology` despite what the doc-string implies.
This PR moves the logic from `set_cosmology` to `get_cosmology`. The former now just calls the latter rather than having duplicate logic.
=> BUG: make `get_cosmology` constistent with `set_cosmology`

bilby/gw/cosmology.py, bilby/gw/prior.py, test/gw/cosmology_test.py
Add the Planck15_LAL cosmology as defined in: https://dcc.ligo.org/DocDB/0167/T2000185/005/LVC_symbol_convention.pdf
Note: there are additional commits in this PR since it requires the PR listed below. It should be rebased before being reviewed.
Requires: https://github.com/bilby-dev/bilby/pull/828
=> ENH: add Planck15_LAL cosmology

test/gw/detector/psd_test.py
Some of the tests were modifying the logger in place and mocking the `warning` method. This breaks the logger for any tests are run after this test, as seen in https://github.com/bilby-dev/bilby/pull/42. I've changed these test to patch the logger instead.
=> TST: patch logger in tests

bilby/gw/source.py, test/gw/source_test.py
=> BUG: changed formatting for unused kwargs error message

bilby/gw/likelihood/relative.py, test/gw/likelihood/relative_binning_test.py
If the last bin index is already chosen to be the last point in the frequency array, we shouldn't increment by 1, else we have an invalid index.
I observed this with very long injections that have power even at the maximum frequency, and thus, the bin selection will already include the last frequency point in the bin indices.
=> [BUG] relative binning - correctly set last bin index

bilby/core/prior/dict.py
I have noticed that for larger numbers of samples, `PriorDict.rescale` becomes quite slow due to the `flatten` operation, which iterates over all entries with a (slow) native python for loop. 
The following PR provides a relatively simple fix that should be able to handle anything `rescale` methods can reasonably throw at it. In my testing, for only one sample, the new version is roughly equivalent to the old version (if anything slightly faster already). For larger counts, the new method is significantly faster.
On a related note, would it not make sense to let the return value have the appropriate shape for `rescale`s of more than one sample?
=> Optimized rescale methods

bilby/core/result.py, test/core/result_test.py
Transfer of https://git.ligo.org/lscsoft/bilby/-/merge_requests/1347
BUG: Make sure outdir is not ignored unnecessarily on manual saving of result file.
=> FEAT: Fix abs/rel path priority in result files.

.github/workflows/publish.yml
Add `needs` to the `pypi-published` step of the `publish.yml` workflow.
This ensured `pypi-published` runs _after_ `build`.
Close #860
=> CI: specify `needs` for `pypi-publish`

CONTRIBUTING.md
As discussed on the dev call, I've added a new section to the contributing guidelines describing how to make releases.
This assumes that the CI works, which should be fixed by https://github.com/bilby-dev/bilby/pull/865
I'm happy to move this elsewhere if people think there's a better place for it.
I also fixed https://github.com/bilby-dev/bilby/issues/805 since it was making changes to the file. The issue was the use of relative paths, so I've changed it to just pull the file from the git repo.
=> DOC: add instructions for making releases

bilby/gw/prior.py, test/gw/prior_test.py
Add attributes and a method that allow the user to check if a `CBCPriorDict` contains any cosmological priors and check they use the same cosmology.
This should simplify adding a cosmology to `bilby_pipe` as it will allows to easily check the priors are valid and then pull the cosmology.
=> ENH: add cosmology to `CBCPriorDict`

bilby/gw/detector/calibration.py
The `correction_type` argument was not added to the `Precomputed` calibration. This PR fixes that.
=> BUG: add correction_type to precomputed calibration

.github/workflows/unit-tests.yml
Temporarily force `matplotlib` < 3.10 in the CI.
**Motivation**
`gwpy` is currently incompatible with `matplotlib` 3.10 (see https://gitlab.com/gwpy/gwpy/-/issues/1786) and this is causing the CI to fail; see https://github.com/bilby-dev/bilby/pull/884
**Details**
Rather than modify the containers, I've just forced `conda` to install a lower version of `matplotlib` before installing `bilby`
**Other notes**
This PR should be reverted once a new release of `gwpy` has been made.
=> CI: temporarily require matplotlib <3.10

.github/workflows/unit-tests.yml
Run unit tests of different python versions and activate conda environment.
**Motivation**
While try to fix the CI issues in https://github.com/bilby-dev/bilby/pull/884, I realised that the conda environment created in the containers is not being activated. This mean that an `conda` commands are not being run in the right env. This can be fixed by activating the environment. Since the environments are named `python<version without dot>` e.g. `python311`, I thought this would a good moment to add different Python versions into the CI.
**Changes**
I've added a `matrix` entry to the `stratergy` section of the unit test CI. This contains the different Python versions along with the short version name (e.g. 311) which is needed to fetch the container.
=> CI: specify python version and activate env

test/core/prior/dict_test.py
Relax the tolerance for the prior test that uses cosmology.
**Motivation**
Due to, I assume, an updated dependency, the exact value returned by `ln_prob` in this test has changed very slightly. This has caused the tests to fail with the following error:
```
FAILED test/core/prior/dict_test.py::TestLoadPriorWithCosmologicalParameters::test_load - AssertionError: -9.360343006800319 != -9.360343006800193
```
see for example https://github.com/bilby-dev/bilby/actions/runs/12686406298/job/35358676377?pr=884.
**Changes**
In order to avoid this and get the CI passing again, I've added a tolerance to the test so that it passes.
**Testing**
I tested this with a new environment that included the fix in https://github.com/bilby-dev/bilby/pull/884 and the tests now pass.
**Other notes**
This PR …
=> TST: relax tolerance for prior test with cosmo parameters

bilby/core/prior/analytical.py
`scipy.special.btdtr` and `scipy.special.btdtri` are deprecated and were removed in `scipy` 1.14.0 (see the docs [here](https://docs.scipy.org/doc/scipy-1.13.0/reference/generated/scipy.special.btdtri.html) and [here](https://docs.scipy.org/doc/scipy-1.13.0/reference/generated/scipy.special.btdtr.html#scipy.special.btdtr)). The PR replaces the import and call with `betainc` and `betaincinv` which are equivalent.
**Motivation**
Since this function has been removed, we have to change the code if we are going to support `scipy` >= 1.14.0.
The CI was failing due to this import. See e.g. https://github.com/bilby-dev/bilby/actions/runs/12650850335
**Testing**
I've run the tests locally and they pass.
**Other notes**
I also reformatted the imports to follow the formatting used by `black`
=> MAINT: avoid call to deprecated `scipy.special.btdtr` and `scipy.special.btdtri` functions

bilby/bilby_mcmc/sampler.py
Ignore the specific error relating to missing whitespace (E226) in the logging out for bilby_MCMC.
**Motivation**
After an update to various dependencies, `f"Temp:{ii}<->{ii+1}|"` was trigger a `flake8` error (226) because of missing whitespace around the operator(s) (not sure if it's a specific operator or all of them). ~~Since these operators are actually just part of the logging statement, this error can be ignored.~~
Colm pointed out the issue was the `i+1` rather than the string.
See e.g. the CI here: https://github.com/bilby-dev/bilby/actions/runs/12686391271/job/35358629525
**Changes**
Fix the fomatting issue,
**Other details**
Closes #889
=> STY: fix style error

test/gw/detector/calibration_test.py
Remove calls to `numpy.alltrue` in the test suite.
This function was deprecated before numpy 2.0 as then removed in 2.0. This causes the test suite to fail if using numpy 2.0.
=> TST: remove calls to deprecated `numpy.alltrue` function

bilby/core/sampler/dynesty.py
Resolves #43 by adding a check to see if the file is empty
=> BUG: Update the resume file check to see if the file is empty

bilby/core/sampler/__init__.py, bilby/core/utils/io.py, bilby/gw/result.py, test/core/result_test.py, test/gw/result_test.py
Add `cosmology` to the `CompactBinaryCoalescenceResult`.
If we run analyses with a different cosmology, I think this should be recorded in the result file. My proposal is to add the `cosmology` in a new dictionary within `meta_data` called `global_meta_data`. This is inline with the changes proposed in https://github.com/bilby-dev/bilby/pull/873. I've implemented it following the same pattern used for other properties, such as the waveform arguments.
Whilst making these changes, I realised that for this to work, the encoding/decoding on astropy objects wasn't working correctly for `hdf5` files. So a lot of changes are related to this.
**Changes**
- Add `cosmology` to the meta data dictionary when calling run sampler
- Add `cosmology` to the meta data dictionary when making an instance of …
=> ENH: add cosmology to CBC result

AUTHORS.md, bilby/gw/result.py
Fixing a small bug in CBCResult. plot_interferometer_waveform_posterior, where the pandas.posterior.iterrows() function sometimes changes dtype of input (e.g. from float to complex), leading to some errors later down the line. Replaced with a very similar method itertuples which preserves dtypes of inputs.
=> [BUG]: fixing dtypes being changed in plot_interferometer_waveform_posterior

.github/workflows/unit-tests.yml
The issue that required this was fixed in gwpy 3.11, see https://gitlab.com/gwpy/gwpy/-/releases/v3.0.11.
I don't think we need to set a minimum version, but we'll see if the CI passes.
=> CI: remove constraint on matplotlib version

bilby/core/sampler/__init__.py, bilby/core/utils/__init__.py, bilby/core/utils/io.py, bilby/core/utils/meta_data.py, bilby/core/utils/random.py, bilby/gw/cosmology.py, bilby/gw/result.py, test/core/utils_test.py
Based on the discussion in https://github.com/bilby-dev/bilby/pull/867, I've made a start on a possible implementation of a global meta data object.
For now, it's just a singleton dictionary that, by default, tracks the `rng`. Things like the `cosmology` can then be added when they're set.
**Motivation**
This change makes it easier to keep track of any global variables and allows us to ensure they're saved in the result file after running a sampler.
**Changes** (updated 27/01/25)
- Add a new `meta_data` submodule and `GlobalMetaData` class
- Add functions for encoding/decoding numpy random generators
- Add test for saving generators
- Extend `seed`, `set_cosmology` and `_set_default_cosmology` to update the global meta data when called.
- Add functions for encoding `UserDict` and …
=> ENH: add global meta data

bilby/gw/prior.py, test/core/prior/prior_test.py, test/gw/prior_test.py
As pointed out in https://arxiv.org/abs/2305.19907. The numerical method we use for the aligned spin prior breaks down in the extreme high SNR regime. This MR adds an exact version when using the default spin prior.
Copy of https://git.ligo.org/lscsoft/bilby/-/merge_requests/1282
=> ENH: Analytic aligned spin

bilby/gw/source.py
Fixes https://github.com/bilby-dev/bilby/issues/908
Restores the waveform_kwarg to specify a numerical relativity file to be `numerical_relativity_file` rather than `numerical_relativity_data` in order to be consistent with [`bilby_pipe`](https://git.ligo.org/lscsoft/bilby_pipe/-/blob/master/bilby_pipe/input.py?ref_type=heads#L433).
Let me know if you prefer to use `numerical_relativity_data` instead and fix this in `bilby_pipe`.
=> Restore numerical_relativity_file kwarg

bilby/gw/prior.py, test/core/prior/prior_test.py
https://github.com/bilby-dev/bilby/pull/849 added a new test to the `prior_test.py` but this test is currently taking ~1 hour total in the CI. To address this, I've added `num_interp` to the `AlignedSpin` prior. 
This allows us to speed up the test but allows the user to configure the interpolation. The defaults are the same (different for each case).
On my laptop, this reduced the time from ~20 minutes to ~ 2 minutes, but we'll see how the CI behaves.
=> ENH: add `num_interp` to `AlignedSpin` prior

bilby/core/result.py, test/core/result_test.py
The raise statement in `get_all_injection_credible_levels` is incorrectly formatted. This PR fixes the formatting.
This wasn't being caught by the existing test, since the error was also a `TypeError`:
```
TypeError: exceptions must derive from BaseException
```
so I've also updated the test to check error message itself.
=> BUG: fix incorrectly formatted raise statement

bilby/core/sampler/__init__.py
Resolves https://github.com/bilby-dev/bilby/issues/606
There has been a very long-standing issue where the `generate_all_cbc_parameter` functions didn't use the correct waveform arguments for injections. I think will resolve that in a generic way as long as the conversion function extracts that information from the likelihood. This now mirrors how the call is made for the posterior samples.
=> BUG: use likelihood for injection conversion function

examples/gw_examples/data_examples/GW150914.py, examples/gw_examples/data_examples/GW190425.py, examples/gw_examples/injection_examples/australian_detector.py, examples/gw_examples/injection_examples/binary_neutron_star_example.py, examples/gw_examples/injection_examples/bns_eos_example.py, examples/gw_examples/injection_examples/bns_polytrope_eos_example.py, examples/gw_examples/injection_examples/bns_spectral_pca_eos_example.py, examples/gw_examples/injection_examples/calibration_example.py, examples/gw_examples/injection_examples/calibration_marginalization_example.py, examples/gw_examples/injection_examples/change_sampled_parameters.py, examples/gw_examples/injection_examples/create_your_own_source_model.py, examples/gw_examples/injection_examples/create_your_own_time_domain_source_model.py, examples/gw_examples/injection_examples/custom_proposal_example.py, examples/gw_examples/injection_examples/eccentric_inspiral.py, examples/gw_examples/injection_examples/fake_sampler_example.py, examples/gw_examples/injection_examples/fast_tutorial.py, examples/gw_examples/injection_examples/how_to_specify_the_prior.py, examples/gw_examples/injection_examples/marginalized_likelihood.py, examples/gw_examples/injection_examples/multiband_example.py, examples/gw_examples/injection_examples/non_tensor.py, examples/gw_examples/injection_examples/relative_binning.py, examples/gw_examples/injection_examples/roq_example.py, examples/gw_examples/injection_examples/sine_gaussian_example.py, examples/tutorials/compare_samplers.ipynb, examples/tutorials/visualising_the_results.ipynb
Added a line in each result of CBC sampling occurrences to specify the result_class to be CBCResult
=> ENH: Added the CBCResult class to all gw examples

bilby/gw/detector/networks.py, test/gw/detector/networks_test.py
Currently, the InterferometerList class has the `plot_data` function for plotting the frequency domain strain for each of the detectors directly using their respective `plot_data` functions. However, to plot the time domain equivalent, one must loop the detectors manually. This PR simply adds an equivalent function for the `plot_time_domain_data` function. Testing has been added that mirrors the `plot_data` testing.
=> ENH: Add InterferometerList time domain plotting

bilby/core/result.py, bilby/core/utils/__init__.py, bilby/core/utils/env.py, bilby/core/utils/meta_data.py, bilby/gw/result.py, docs/faq.txt, examples/gw_examples/injection_examples/fast_tutorial.py, test/core/utils_test.py, test/gw/result_test.py
Rework `GlobalMetaData` to inherit from `dict` rather than `UserDict`.
This means any checks for `isinstance(o, dict)` will return `True` rather than `False`. This will hopefully address the issue seen in some downstream packages.
I've also added an environment variable called `BILBY_INCLUDE_GLOBAL_META_DATA` (open to suggestions for a better name) that toggles whether the meta data is included or not in the result object. By default, this is False, meaning it should be backwards compatible.
I also had to tweak the `cosmology` property in the CBC result now that it isn't always present.
=> MAINT: rework `GlobalMetaData` to inherit from `dict`

bilby/core/result.py
Ensure the output directory exists when checkpointing the reweighting process.
**Context**
When using reweighting results using `bilby_pipe` if `outdir/result` does not exist, the process fails with the following error:
```
FileNotFoundError: [Errno 2] No such file or directory: 'high_spin_reweighting_marg_outdir/result/bilby-IMRPhenomPv2-NRTidalv2-RB-highspin-3_reweighted_reweight_resume.pkl
``` 
As fas as I can tell, this is because `high_spin_reweighting_marg_outdir/result` is not made automatically.
**Changes**
In `get_weights_for_reweighting` ensure the directory for the resume file exists.
=> BUG: ensure directory exists when reweighting

bilby/core/sampler/dynesty.py
Sometimes, one wants to explore lower thresholds for the stopping criterion. Without this change the values for dlogz below 1e-3 will be shown as 0.000. With this change, these numbers will be printed in scientific notation after they become sufficiently small.
=> ENH: Dynesty: Allow printing dlogz below 1e-3

bilby/core/sampler/__init__.py, bilby/gw/conversion.py, test/gw/conversion_test.py
#900 introduced a bug in the recovery of distance posteriors when using distance marginalization (among other things). This resolves the issue, but I'm not convinced that this is the best solution.
In general, I think this kind of situation is fairly unavoidable as we store the parameter values in the likelihood.
=> BUG: fix injection parameters being fixed during recovery

bilby/gw/conversion.py
In the conditional of `generate_posterior_samples_from_marginalized_likelihood`, checks for the value of `likelihood.time_reference` which will actually occur. Fixes https://github.com/bilby-dev/bilby/issues/929.
=> BUG: Use "geocent" not "geocenter" where appropriate

CHANGELOG.md
Update the changelog for v2.5.1.
I also added the dates for 2.4.0 and 2.50 since they were missing. I've not added one for 2.5.1 since I'm not sure exactly when we'll make the release.
=> CHANGELOG: update for v2.5.1

README.rst
The link for opening bilby_pipe issues currently is broken as it points within the bilby-dec github, this MR restores it to point to the LVK gitlab.
=> DOC:Fixed README link for opening bilby_pipe issues

bilby/core/prior/dict.py, test/core/prior/dict_test.py
This pull request fixes the bug reported in #938 and #944.
The issue is that, even for 100% efficient priors, like
```python
priors = bilby.core.prior.PriorDict()
priors["mass_1"] = bilby.core.prior.Uniform(minimum=1.2, maximum=2)
```
the following warning shows up when drawing a sufficiently large number of samples [here `priors.sample(1_000_000)`]:
```
21:25 bilby WARNING : Prior sampling efficiency is very low, please verify its validity.
```
The warning materialises because the `sample_subset_constrained` method of `PriorDict` assumes that the priors include at least one `Constraint` prior.
I have also added a very simple unit test to check for this warning.
=> BUG: Fix sampling efficiency warning

bilby/core/sampler/__init__.py
As described in #927, if using the `run_sampler` function, the default value of `use_ratio` is `None`, which actually results in the likelihood ratio being calculated if the likelihood contains a valid `log_likelihood_ratio` method. This is at odds with the doc string which states that the default value of `use_ratio` is `False`. This PR fixes the doc string to be consistent with the actual way the code works.
=> DOC: Correct docs for use_ratio argument of run_sampler

bilby/gw/detector/interferometer.py, test/gw/detector/interferometer_test.py
This PR fixes a longstanding bug in the likelihood when using windowed time-domain data. The addition of the window factor was due to a misunderstanding of what quantity should be whitened. The change made here will ensure that the data containing the signal is correctly whitened.
Closes #869
=> BUG: remove incorrect window-based PSD scaling

containers/env-template.yml
After we fix the numpy incompatibilities in #979 and #980 the remaining numpy issue will be in dynesty, since that will need #950 we should be able to remove this pin when a new release of dynesty is available.
=> TST: Restrict numpy version for dynesty compatibility

bilby/bilby_mcmc/sampler.py, bilby/core/prior/interpolated.py, bilby/core/sampler/ptemcee.py, bilby/gw/prior.py, examples/core_examples/multivariate_gaussian_prior.py, test/core/prior/prior_test.py, test/gw/likelihood/marginalization_test.py
`trapz` was removed from numpy in a recent release in favour of `trapezoid`. This PR changes the instances of `np.trapz` throughout the codebase.
=> MAINT: np.trapz -> np.trapezoid

bilby/gw/cosmology.py
Update the Planck15-LAL cosmology to use the variables exposed in https://git.ligo.org/lscsoft/lalsuite/-/merge_requests/2368.
Since older versions of LAL won't support this, I've used a try/except to fall back to manual values.
=> MAINT: define Planck15-LAL cosmology using LAL constants

.github/workflows/basic-install.yml, .github/workflows/pages.yml, .github/workflows/pre-commit.yml, .github/workflows/unit-tests.yml
Add `merge_group` to the CI workflows that usually run for PRs. This will enable us to use [merge queues](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#managing-a-merge-queue)
Closes #895
=> CI: add merge_group to enable merge queue

CONTRIBUTING.md, pyproject.toml
Change how we make releases to use release branches.
This should make it easier to backport bug fixes to versions being used in production analyses.
Note: this requires https://github.com/bilby-dev/bilby/pull/952
=> BLD: use release branches

bilby/gw/likelihood/roq.py, test/gw/likelihood_test.py
This was slated for v2.2, but I guess we missed that...
=> MAINT: remove unsupported roq json weight file format
